name: Build and Test
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: 'recursive'
      - uses: cachix/install-nix-action@v12
      - run: nix-build --arg cmakeFlags '["-DBUILD_TESTING=TRUE" "-DBRANCH=branched"]'
      - run: mkdir build-result
      - run: cp -r result/* build-result/
      - uses: actions/upload-artifact@v2
        with:
          name: build-result
          path: build-result/

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/download-artifact@v2
        with:
          name: build-result
          path: ./build-result/
      - uses: cachix/install-nix-action@v12
      - run: nix-shell --run ./scripts/setup.sh
      - run: chmod +x ./build-result/bin/kvstore_test
      - run: nix-shell --run ./build-result/bin/kvstore_test
