name: Build
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: 'recursive'
      - uses: cachix/install-nix-action@v12
      - run: nix-build --arg cmakeFlags '["-DBUILD_TESTING=TRUE" "-DBRANCH=branched"]'
      - run: mkdir build-result
      - run: cp -r result/* build-result/
      - uses: actions/upload-artifact@v2
        with:
          name: build-result
          path: build-result/
      # Test does not work because no avx instructions on test machine.
      # - run: result/bin/kvstore_test
