name: Build and Test
on:
  pull_request:
  push:
jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: 'recursive'
      - uses: cachix/install-nix-action@v16
        with:
          install_url: https://releases.nixos.org/nix/nix-2.4/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix develop .#build
      - run: mkdir build && cd build && cmake .. -G Ninja -DBUILD_TESTING=TRUE -DBRANCH=branched -DHUGEPAGES=FALSE
      - run: ninja
      - run: ctest -V
